#!/bin/sh

### BEGIN INIT INFO
# Provides:          fake-hwclock
# Required-Start:
# Required-Stop:     umountroot
# Should-Stop:       
# X-Start-Before:    checkroot
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Restore / save the current clock
# Description:       
### END INIT INFO

set -e

# Include core init functions if needed
. /lib/lsb/init-functions

case "${1:-}" in
  stop|reload|restart|force-reload)
        echo "Saving system time to external RTC."
        /opt/set-time-to-rtc.sh;
        echo "RTC set result $?."
	;;

  start)
        echo "Loading system time from external RTC."
        /opt/set-system-time-from-rtc.sh;
        echo "RTC load result $?."
	;;

  *)
        echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
